#!/usr/bin/env python3
"""Builds a release from file_inventory.txt.

Every file marked "N" is grouped by its top-level directory (or "."
for a loose top-level file) and tarred into dist/, splitting anything over
1.5 GiB into numbered parts to stay under GitHub's 2 GiB per-asset limit.
manifest.json and each affected directory's README.md file-list section are
rewritten to match, and .gitignore's auto-generated block is updated to
cover exactly those "N" files.

Every file marked "Y" is left alone on disk; dist/git_add_committed_files.sh
is written to `git add` all of them in one step.

Tarballs are built byte-for-byte reproducibly (fixed gzip timestamp, zeroed
owner info) -- rerunning this with unchanged file content reproduces the
same tarball bytes and sha256, so it won't silently desync manifest.json
from an already-uploaded release.

Usage: scripts/package_data_release.py <release-tag>
"""
import datetime
import gzip
import hashlib
import json
import os
import sys
import tarfile

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INVENTORY = os.path.join(REPO_ROOT, "file_inventory.txt")
DIST_DIR = os.path.join(REPO_ROOT, "dist")
MANIFEST = os.path.join(REPO_ROOT, "manifest.json")
GITIGNORE = os.path.join(REPO_ROOT, ".gitignore")
UPDATE_README = os.path.join(REPO_ROOT, "scripts", "update_readme_filelist.py")

# Stay safely under GitHub's 2 GiB (2147483648 byte) per-asset hard limit.
MAX_CHUNK_BYTES = int(1.5 * 1024 ** 3)

GITIGNORE_START = "# nusyst_data:inventory:start (auto-generated by scripts/package_data_release.py - do not edit by hand)"
GITIGNORE_END = "# nusyst_data:inventory:end"


def load_inventory():
    y_files, n_files = [], []
    with open(INVENTORY) as fh:
        for lineno, raw in enumerate(fh, 1):
            line = raw.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            path, _, flag = line.rpartition(" ")
            flag = flag.strip().upper()
            if not path or flag not in ("Y", "N"):
                sys.exit("file_inventory.txt:%d: malformed line (want \"<path> <Y|N>\"): %r" % (lineno, raw))
            full = os.path.join(REPO_ROOT, path)
            if not os.path.isfile(full):
                print("warning: %s is listed in file_inventory.txt but no longer exists on "
                      "disk; skipping (re-run scripts/scan_files.py to refresh)" % path, file=sys.stderr)
                continue
            (y_files if flag == "Y" else n_files).append(path)
    return sorted(y_files), sorted(n_files)


def group_by_top_dir(paths):
    groups = {}
    for p in paths:
        top = p.split("/", 1)[0] if "/" in p else "."
        groups.setdefault(top, []).append(p)
    return groups


def chunk_by_size(paths, max_bytes):
    chunks, current, current_bytes = [], [], 0
    for p in paths:
        size = os.path.getsize(os.path.join(REPO_ROOT, p))
        if current and current_bytes + size > max_bytes:
            chunks.append(current)
            current, current_bytes = [], 0
        current.append(p)
        current_bytes += size
    if current:
        chunks.append(current)
    return chunks


def arcname_of(rel_path, group):
    """Path a file should have inside its tarball, relative to extract_to."""
    return rel_path.split("/", 1)[1] if group != "." else rel_path


def make_tarball(out_path, members, group):
    """Write a reproducible .tar.gz: fixed gzip mtime, zeroed owner info, so
    unchanged inputs always produce the same bytes (and sha256)."""
    with gzip.GzipFile(out_path, mode="wb", mtime=0) as gz:
        with tarfile.open(fileobj=gz, mode="w") as tf:
            for rel in members:
                full = os.path.join(REPO_ROOT, rel)
                arcname = arcname_of(rel, group)
                ti = tf.gettarinfo(full, arcname=arcname)
                ti.uid = ti.gid = 0
                ti.uname = ti.gname = ""
                with open(full, "rb") as f:
                    tf.addfile(ti, f)


def sha256_of(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for block in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def update_readme(readme_dir, release_tag, group, members):
    import subprocess
    names = [arcname_of(p, group) for p in members]
    subprocess.check_call([
        sys.executable, UPDATE_README,
        os.path.join(readme_dir, "README.md"), release_tag, group,
    ] + names)


FILELIST_MARKER = "<!-- nusyst_data:filelist:start -->"


def find_marked_readmes():
    """(group, readme_path) for every README.md in the repo that already has
    a file-list marker section -- used to clear stale entries for a group
    that dropped to zero "N" files (it would otherwise never get revisited,
    since the main loop only touches groups that still have files)."""
    candidates = [(".", os.path.join(REPO_ROOT, "README.md"))]
    for entry in sorted(os.listdir(REPO_ROOT)):
        full = os.path.join(REPO_ROOT, entry)
        if os.path.isdir(full) and entry not in (".git", "dist", "__pycache__", "scripts"):
            candidates.append((entry, os.path.join(full, "README.md")))
    for group, path in candidates:
        if os.path.exists(path):
            with open(path) as fh:
                if FILELIST_MARKER in fh.read():
                    yield group, path


def update_gitignore(n_files):
    content = ""
    if os.path.exists(GITIGNORE):
        with open(GITIGNORE) as fh:
            content = fh.read()

    block = "\n".join([GITIGNORE_START] + sorted(n_files) + [GITIGNORE_END])
    start = content.find(GITIGNORE_START)
    end = content.find(GITIGNORE_END)
    if start != -1 and end != -1:
        content = content[:start] + block + content[end + len(GITIGNORE_END):]
    else:
        sep = "" if (not content or content.endswith("\n")) else "\n"
        content = content + sep + "\n" + block + "\n"

    with open(GITIGNORE, "w") as fh:
        fh.write(content)
    print("Updated %s (%d entries)" % (GITIGNORE, len(n_files)))


def write_git_add_script(y_files):
    os.makedirs(DIST_DIR, exist_ok=True)
    path = os.path.join(DIST_DIR, "git_add_committed_files.sh")
    with open(path, "w") as fh:
        fh.write("#!/usr/bin/env bash\n")
        fh.write("# Generated by scripts/package_data_release.py.\n")
        fh.write('# Stages every file_inventory.txt "Y" file with git add.\n')
        fh.write("set -euo pipefail\n")
        fh.write('cd "%s"\n' % REPO_ROOT)
        if y_files:
            fh.write("git add -- \\\n")
            for i, p in enumerate(y_files):
                cont = " \\\n" if i < len(y_files) - 1 else "\n"
                fh.write('  "%s"%s' % (p, cont))
        else:
            fh.write("# (no \"Y\" files in file_inventory.txt)\n")
    os.chmod(path, 0o755)
    return path


def main():
    if len(sys.argv) != 2 or not sys.argv[1]:
        sys.exit("Usage: %s <release-tag>\n  e.g. %s v01_01_00" % (sys.argv[0], sys.argv[0]))
    release_tag = sys.argv[1]

    if not os.path.exists(INVENTORY):
        sys.exit("file_inventory.txt not found. Run scripts/scan_files.py first.")

    y_files, n_files = load_inventory()
    print("Release tag: %s" % release_tag)
    print("  %d file(s) to commit to git directly" % len(y_files))
    print("  %d file(s) to bundle into release tarballs" % len(n_files))
    print()

    os.makedirs(DIST_DIR, exist_ok=True)
    for f in os.listdir(DIST_DIR):
        full = os.path.join(DIST_DIR, f)
        if os.path.isfile(full):
            os.remove(full)

    assets = []
    n_groups = group_by_top_dir(n_files)
    for group, path in find_marked_readmes():
        if group not in n_groups:
            readme_dir = os.path.dirname(path)
            update_readme(readme_dir, release_tag, group, [])
            print("==> %s: no \"N\" files anymore, cleared its README.md file-list section" % group)
    for group, paths in sorted(n_groups.items()):
        paths = sorted(paths)
        chunks = chunk_by_size(paths, MAX_CHUNK_BYTES)
        multi = len(chunks) > 1
        base_name = "toplevel" if group == "." else group
        print("==> %s (%d file(s), %d asset(s))" % (group, len(paths), len(chunks)))
        for i, chunk in enumerate(chunks, 1):
            name = "%s.part%02d.tar.gz" % (base_name, i) if multi else "%s.tar.gz" % base_name
            out_path = os.path.join(DIST_DIR, name)
            make_tarball(out_path, chunk, group)
            sha = sha256_of(out_path)
            size = os.path.getsize(out_path)
            assets.append({"file": name, "extract_to": group, "sha256": sha, "bytes": size})
            print("  wrote %s (%.1f MB, sha256=%s)" % (name, size / 1e6, sha))

        readme_dir = REPO_ROOT if group == "." else os.path.join(REPO_ROOT, group)
        update_readme(readme_dir, release_tag, group, paths)

    manifest = {
        "schemaVersion": 1,
        "releaseTag": release_tag,
        "generatedAt": datetime.datetime.now(datetime.timezone.utc).isoformat().replace("+00:00", "Z"),
        "assets": assets,
    }
    with open(MANIFEST, "w") as fh:
        json.dump(manifest, fh, indent=2)
        fh.write("\n")
    print()
    print("Wrote %s" % MANIFEST)

    update_gitignore(n_files)
    add_script = write_git_add_script(y_files)
    print("Wrote %s" % add_script)

    print()
    print("Next steps:")
    print("  1. Create the release and upload the tarballs (needs 'gh' installed and authenticated):")
    print("       gh release create %s dist/*.tar.gz \\" % release_tag)
    print("         --repo NuSystematics/nusyst_data \\")
    print('         --title "%s" --notes "Data release %s"' % (release_tag, release_tag))
    print()
    print("  2. Stage the git-tracked files and commit everything:")
    print("       dist/git_add_committed_files.sh")
    print("       git add manifest.json .gitignore file_inventory.txt")
    print('       git commit -m "Update data release to %s"' % release_tag)
    print("       git push")


if __name__ == "__main__":
    main()
